### ISSUE TITLE
代码报错提示

### ISSUE THREAD

**Issue by hello-jo** [IvanXie416/HECPG#1]
您好，我在运行训练代码时出现报错，问题在于hy_attention.py 中的第50行： b, num_centroids, c = h.shape ，输出h维度分别为torch.Size([1,244,1024])   torch.Size([1,291,1024])   torch.Size([1,1,244,256])， h 变为了四维向量，请告诉我是哪里配置出现问题吗？期待您的回复于解答，非常感谢。运行错误提示见下图：
![微信图片_20240604162803](https://github.com/IvanXie416/HECPG/assets/82424028/a745b695-bdf5-4568-8eb9-e06c977f1ba8)

**Comment by IvanXie416** [comment]
感谢您的关注。是不是数据读取出了问题？正常的流程是：h原本是二维的（例如: [244, 1024]），通过unsqueeze操作变为三维（例如: [1, 244, 1024]）再输入到HypAttention。
